# Generated by Django 5.2.4 on 2025-07-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
