# Generated by Django 5.2.4 on 2025-07-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_query_is_anonymous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='college',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Junior', 'Junior'), ('Senior', 'Senior'), ('Doctor', 'Doctor')], max_length=10),
        ),
    ]
