# Generated by Django 5.2.4 on 2025-07-05 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_alter_customuser_college_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='body',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='message',
            name='subject',
        ),
    ]
