# Generated by Django 5.2.4 on 2025-07-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0010_alter_customuser_college_alter_profile_following_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default='avatars/default.png', upload_to='avatars/'),
        ),
    ]
